mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='delete'),
    path('create/', views.QuestionCreateView.as_view(), name='create'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from .models import Choice, Question


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']
        widgets = {
            'question_text': forms.Textarea,
            'pub_date': DateTimeInput()
        }

mysite/polls/views.py
from .forms import QuestionForm
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.db.models import Sum


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class QuestionDeleteView(generic.DeleteView):
    model = Question
    template_name = "polls/delete_question.html"

    def get_success_url(self):
        return reverse_lazy("polls:index")

    def get_context_data(self, **kwargs):
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        num_votes = question.choice_set.aggregate(num_votes=Sum('votes'))
        context = super(QuestionDeleteView, self).get_context_data(**kwargs)
        context["num_votes"] = num_votes["num_votes"]
        return context


class QuestionCreateView(generic.CreateView):
    model = Question
    form_class = QuestionForm
    template_name = "polls/create_question.html"

    def form_valid(self, QuestionForm):
        question = QuestionForm.save()
        choices_list = list(
            filter(("").__ne__, self.request.POST.getlist('choices')))
        for choice in choices_list:
            Choice.objects.create(question=question, choice_text=choice)
        return super(QuestionCreateView, self).form_valid(QuestionForm)

    def get_success_url(self):
        return reverse_lazy('polls:index')

mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>{% block title %} {% endblock %}</title>
</head>

<body>
  {% block content %}
  {% endblock %}

</body>
<script>
  $(document).ready(function () {
    const max_fields = 10; //maximum input boxes allowed
    const wrapper = $(".input_fields_wrap"); //Fields wrapper
    const add_button = $(".add_field_button"); //Add button ID

    let x = 1; //initlal text box count
    $(add_button).click(function (e) { //on add input button click
      e.preventDefault();
      if (x < max_fields) { //max input box allowed
        x++; //text box increment
        $(wrapper).append('<div class = "choice-field"><input type="text" name="choices"/><a href="#" class="remove_field btn btn-outline-danger btn-sm">Remove</a></div>'); //add input box
      }
    });

    $(wrapper).on("click", ".remove_field", function (e) { //user click on remove text
      e.preventDefault();
      $(this).parent('div').remove();
      x--;
    })
  });
</script>

</html>

mysite/polls/templates/polls/create_question.html
{% extends "polls/base.html" %}

{% block title %} Create Question{% endblock %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{request.path}}">Create New Question</a>
    <a class="navbar-brand" href="{% url 'polls:index'%}">Home</a>
  </div>
</nav>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="input_fields_wrap">
    <button class="add_field_button btn btn-outline-primary">Add More Choice</button><br>
    <div><input type="text" name="choices"></div>
  </div>
  <p>
    <a class="btn btn-secondary" href="{% url 'polls:index'%}">Back</a>
    <input class="btn btn-success" type="submit" value="Save">
  </p>
</form>

{% endblock %}

mysite/polls/templates/polls/delete_question.html
{% extends "polls/base.html" %}

{% block title %} Delete Question{% endblock %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{request.path}}">Delete Question</a>
    <a class="navbar-brand" href="{% url 'polls:index'%}">Home</a>
  </div>
</nav>
<form action="" method="POST">
  {% csrf_token %}

  <h3>Do you want to delete the question "{{ question.question_text }}"?</h3>
  {% if num_votes %}
  <h4>This question has {{ num_votes }} votes</h4>
  {% else %}
  <h4>This question has 0 votes</h4>
  {% endif %}

  <p><a class="btn btn-secondary" href="{% url 'polls:index' %}">Back</a> <input class="btn btn-success" type='submit'
      value='Yes' /> </p>
</form>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %} Question Detail{% endblock %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{request.path}}">Vote Choices</a>
    <a class="navbar-brand" href="{% url 'polls:index'%}">Home</a>
  </div>
</nav>
<h1>{{question.question_text}}</h1>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form class="vote-form" action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">
    {{choice.choice_text}}
  </label><br>
  {% endfor %}
  <a class="btn btn-secondary" href="{% url 'polls:index' %}">Back</a>
  <input class="btn btn-primary" type="submit" value="Vote">
</form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block title %}
Questions Page
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{request.path}}">Questions</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="btn btn-outline-success" href="{% url 'polls:create' %}">Create New Questions</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% if latest_question_list %}
<table class="table">
  <thead class="thead-dark text-center">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Questions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody class="text-center">
    {% for question in latest_question_list %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ question.question_text }}</td>
      <td><a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote</a></td>
      <td><a class="btn btn-danger" href="{% url 'polls:delete' question.id %}">Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-warning" role="alert">
  <p>No polls are available.</p>
</div>
{% endif %}

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends "polls/base.html" %}


{% block title %}
Result
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{request.path}}">Results</a>
    <a class="navbar-brand" href="{% url 'polls:index'%}">Home</a>
  </div>
</nav>
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
  </li>
  {% endfor %}
</ul>

<a class="btn btn-primary" href="{% url 'polls:detail' question.id %}"> Vote again?</a>

{% endblock %}